### DISCUSSION TITLE
I'm using the remark in a GitHub Action, how to I change the settings for autoescape? I'm new at this.

### DISCUSSION THREAD

**Discussion by Expoverse** [remarkjs/remark#1122] [Q&A] [answered]
I'm using remark and remark-cli

Here is my GitHub action configuration
```
on: push
name: Remark
jobs:
  generateNewMarkdown:
    name: Remark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run remark cli
        uses: tj-actions/remark@v3
        with:
          plugins: |
             remark-toc
             remark-frontmatter
          files: |
             *.md
          rc_path: .remarkrc.yml   
      - name: Verify Changed files
        uses: tj-actions/verify-changed-files@v13
        id: verify-changed-files
        with:
          files: |
             *.md         
      - name: Create Pull Request
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        uses: peter-evans/create-pull-request@v4
        with:
          base: "master"
          title: "Remark Processor"
          branch: "chore/update-markdown"
          commit-message: "Updated markdown content"
          body: "Updated markdown content format as set in .remarkrc.yml"
          token: ${{ github.token }}
```
Here is my .remarkrc.yml configuration
```
settings:
  bullet: "-"
  #rule: '-'
plugins:
  # Check that markdown is consistent.
  #- remark-preset-lint-consistent
  # Few recommended rules.
  #- remark-preset-lint-recommended
  # Generate a table of contents in `## Contents`
  - - remark-toc
    - heading: contents
  - - remark-frontmatter
    - type: 'yaml'
      marker: '-'
```

The problem with escaping my content in my markdown file. Examples are in the pull request generated by remark output
Expoverse/content#7

**& is being escaped in URLS**
Original: 
```
Creating an [issue link](https://github.com/Expoverse/content/issues/new?assignees=&labels=&template=content-bug.yml)
```

Escaped version?: 
```
Creating an [issue link](https://github.com/Expoverse/content/issues/new?assignees=\&labels=\&template=content-bug.yml)
```

**[ is being escaped in strong**
Original: 
```
A calendar icon on an HTML input type date **(input[type=”date”])** can be removed using CSS selectors and properties that target the input element calendar-picker-indicator. When removing a calendar icon, we need to use a **::-webkit-calendar-picker-indicator** pseudo-element, as the calendar icon cannot be selected using standard CSS selectors.
```

Escaped version?: 
```
A calendar icon on an HTML input type date **(input\[type=”date”])** can be removed using CSS selectors and properties that target the input element calendar-picker-indicator. When removing a calendar icon, we need to use a **::-webkit-calendar-picker-indicator** pseudo-element, as the calendar icon cannot be selected using standard CSS selectors.
```

How do I change these settings, I read something about autoescape but I can't find any documentation if this is related to the problem.
