### DISCUSSION TITLE
How do I have large headers

### DISCUSSION THREAD

**Discussion by ARR4NN** [remarkjs/remark#1142] [Q&A] [answered]
The standard for markdown is hastags for large headers
# like this
but when I use them in my reactMarkdown they do not change size
```js
const MarkdownPage = ({ content }) => {
  const testcontent = "# Hello"
  return (
    <div className='MarkdownContainer'>
         <ReactMarkdown
              remarkPlugins={[remarkGfm, remarkBreaks]}
              rehypePlugins={[rehypeRaw,rehypeFormat]}
              children={testcontent}
         />
  </div>
  )
}
```
I have very limited styling 

```css
.MarkdownContainer {
	margin-top: 40px;
	display: flex;
	align-items: center;
	justify-content: center;
	align-content: center;
	text-align: center;
}


```
