### DISCUSSION TITLE
"lint-table-pipe-alignment" rule does not trigger

### DISCUSSION THREAD

**Discussion by sappelhoff** [remarkjs/remark#709] [Q&A] [answered]
Hi all,

since upgrading remark and the presets, the table pipe rules (such as [remark-lint-table-pipe-alignment](https://github.com/remarkjs/remark-lint/tree/main/packages/remark-lint-table-pipe-alignment)) do not work anymore, see: https://github.com/bids-standard/bids-specification/pull/791/files#r625066294

Please let me quickly outline my setup, so that perhaps an experienced user can already spot a mistake that I am doing. I'll be adding links to the PR that I am currently working on (and that's failing)

I have this file of requirements to install: [npm-requirements.txt](https://github.com/bids-standard/bids-specification/pull/791/files#r625064868)

```text
remark-cli@9.0.0
remark-preset-lint-recommended@5.0.0
remark-preset-lint-markdown-style-guide@4.0.0
remark-lint-no-trailing-spaces@2
```

This is getting installed in GitHub Actions [like so](https://github.com/bids-standard/bids-specification/pull/791/files#r628519019):

```yml
name: Check Markdown style

on: [push, pull_request]

jobs:
  markdown-style:
    runs-on : ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup NodeJS
      uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: Install dependencies
      run: npm install `cat npm-requirements.txt`
    - name: Run style checks
      # see: https://stackoverflow.com/a/39991116/5201771
      # alternative (probably): npx remark ...
      run: npm run env -- remark src/*.md src/*/*.md --frail --rc-path .remarkrc
```

See that my command (`npx remark src/*.md src/*/*.md --frail --rc-path .remarkrc`) makes use of a `.remarkrc` file. 

[That's the one](https://github.com/bids-standard/bids-specification/pull/791/files#r625065353):

```json
{
  "plugins": [
    "preset-lint-markdown-style-guide",
    "preset-lint-recommended",
    ["lint-no-duplicate-headings", false],
    ["lint-list-item-indent", "tab-size"],
    ["lint-emphasis-marker", "consistent"],
    ["lint-maximum-line-length", false],
    ["lint-maximum-heading-length", false],
    ["lint-no-shortcut-reference-link", false],
    ["lint-no-trailing-spaces"],
    ["lint-no-undefined-references", false]
  ]
}

```

I hope this looks correct to you so far. (Because it does look good to me).

**However** this setup does not detect misaligned table pipes, [like this one](https://github.com/bids-standard/bids-specification/pull/791/files#r625066294):

```markdown
| **Column name** | **Requirement level** | **Description**                     |
| --------------- | --------------------- | ----------------------------------- |
| name            | REQUIRED              | Name of the electrode.              |
| x               | REQUIRED              | Recorded position along the x-axis.   |
| y               | REQUIRED              | Recorded position along the y-axis. |
```

I don't know how to continue with debugging this. Can somebody please help me go in the right direction?

Thanks!

Stefan
