### ISSUE TITLE
1:1: Incorrectly eaten value

### ISSUE THREAD

**Issue by martin-riley** [remarkjs/remark#491]
### Markdown file created in VS-Code not working in CMS

Describe your issue here.

Markdown page created by hand in VS-Code not able to render in CMS. Error reported as: `1:1: Incorrectly eaten value` Page renders correctly in `markdown-to-jsx` 
```markdown
---
title: Picture responsive test
metaDescription: Responsive images
date: 2012-04-01T19:31:20.591Z
map: false
calendar: false
paypal: false
---

![](/img/church-building.jpg "UBC building")

---

![portrait align-centre](/img/bms-logo.jpg "Baptist Mission logo")

---

![w50%](/img/church-building.jpg "UBC building")

---

![w25%](/img/church-building.jpg "UBC building")
```

### Your environment

*   **OS**: macOS Catalina (Version: 1.45.0)
*   **Packages** used:  
    "dateformat": "^3.0.3",
    "gray-matter": "^4.0.2",
    "markdown-to-jsx": "^6.11.1",
    "next": "^9.3.5",
    "raw-loader": "^4.0.1",
    "react": "^16.13.0",
    "react-dom": "^16.13.0",
    "react-h5-audio-player": "^3.0.5",
    "react-player": "^1.15.3"
*   **Env**: Node: v12.16.1, NPM: 6.13.4, Chrome: 81.0.4044.138 (Official Build) (64-bit)

### Steps to reproduce

Tell us how to reproduce this issue.  Load markdown page using `config.yml`.
```yml
- name: "pages"
    label: "Pages"
    label_singular: "Page"
    description: "Create or update standard pages on the site"
    folder: "_page-content"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string", hint: "The page title, note you will need to know this to add to the menu."}
      - { label: "Search Engine Description", name: "metaDescription", widget: "string", , default: false, hint: "Used in search engine result pages, use words which describe the page content."}
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown", hint: "For image alignment: align-right | align-left | thumb-50 | thumb-25"}
      - { label: "Enable Map", name: "map", widget: "boolean", default: false, hint: "Add church map to this page" }
      - { label: "Enable Calendar", name: "calendar", widget: "boolean", default: false, hint: "Add church calendar to this page" }
      - { label: "PayPal Donation", name: "paypal", widget: "boolean", default: false, hint: "Add church donation widget to this page" }
```

🎉 BONUS POINTS for creating a [minimal reproduction](https://stackoverflow.com/help/mcve) and uploading it to GitHub.  This will get you the fastest support.  🎉

### Expected behaviour

Page should load within the CMS.

### Actual behaviour

Page does not render and error is reported: 1:1: Incorrectly eaten value: please report this warning on http://git.io/vg5Ft
