### ISSUE TITLE
"Turning off a tokenizer" is misleading

### ISSUE THREAD

**Issue by farcaller** [remarkjs/remark#529]
### Subject of the issue

The documentation suggests that you can use the following snippet to turn off a tokenizer:

```
remarkParse.Parser.prototype.blockTokenizers.indentedCode = indentedCode

function indentedCode() {
  return true
}
```

or use remark-disable-tokenizers, whose noop is effectively the same:

```
const noop = () => true
```

However, returning `true` signals to `interrupt()` that the tokenizer actually did something, i.e. it successfully tokenized the input. Same applies to the documentation where it suggests that the tokeniser returns either a truthful `Node` or `true` if the token was found.

This breaks e.g. new line parsing in paragraphs (see below).

### Your environment

*   **Packages**: remark-parse 8.0.3

### Steps to reproduce

```js
var unified = require("unified");
var markdown = require("remark-parse");
const remarkDisableTokenizers = require('remark-disable-tokenizers');
const YAML = require('json-to-pretty-yaml');

var tree = unified()
  .use(markdown)
  .use(remarkDisableTokenizers, { block: ['html'], inline: ['html'] })
  .parse(`hello\nworld`);

function trimPos(node) {
  delete node.position;
  if (!node.children) return;
  for (const c of node.children) {
    trimPos(c);
  }
  return node;
}

tree = trimPos(tree);

var out = YAML.stringify(tree);
console.log(out)
```

### Expected behavior

```yaml
type: "root"
children:
  - type: "paragraph"
    children:
      - type: "text"
        value: "hello\nworld"
```

### Actual behavior

```yaml
type: "root"
children:
  - type: "paragraph"
    children:
      - type: "text"
        value: "hello"
  - type: "paragraph"
    children:
      - type: "text"
        value: "world"
```

### Workaround

Replacing `remarkDisableTokenizers` with the `markdown.Parser.prototype.blockTokenizers.html = () => false;` fixes the issue.

Thus I conclude that the documentation is in the wrong and you should suggest to return false to disable a tokenizer.
